### ISSUE TITLE
quickstart.sh  ^M need removed

### ISSUE THREAD

**Issue by cloudusers** [vipshop/Saturn#129]
before start quickstart.sh

should execute such
vim quickstart.sh
:%s/^M//g

**Comment by hebelala** [comment]
I have not found the ^M in quickstart.sh file, what's you point...

**Comment by cloudusers** [comment]
vim -b quickstart.sh
you will find ^M at the end of some lines
(i think may edit it in window env.......)

or
when your run sh quickstart.sh , it not work and print error msg (for ^M lines)


best regards

**Comment by hebelala** [comment]
oh, I see

**Comment by cloudusers** [comment]
OK
