### ISSUE TITLE
REG_CENTER_JSON_PATH环境变量是否必填?

### ISSUE THREAD

**Issue by henryZ** [vipshop/Saturn#146]
在启动SaturnConsoleApp的main方法时,会报空指针异常,原因是环境变量REG_CENTER_JSON_PATH没有设置,导致RegistryCenterServiceImpl类的138行new File(SaturnEnvProperties.REG_CENTER_JSON_FILE)抛出nullPointException. 但是SaturnEnvProperties中没有看到对环境变量REG_CENTER_JSON_PATH为null时的判断.

**Comment by hebelala** [comment]
非必填

**Comment by hebelala** [comment]
@henryZ  拉下	ea6ffd0提交的代码，试试看是否可以？

**Comment by henryZ** [comment]
如果是非必填，那现在抛出异常应该是个bug了




发自网易邮箱大师
在2017年05月10日 11:22，hebelala 写道：

非必填

**Comment by henryZ** [comment]
👌




发自网易邮箱大师
在2017年05月10日 11:24，hebelala 写道：

@henryZ 拉下 ea6ffd0提交的代码，试试看是否可以？

**Comment by henryZ** [comment]
已经解决,谢谢
