### ISSUE TITLE
文档的小问题

### ISSUE THREAD

**Issue by henryZ** [vipshop/Saturn#152]
在dashboard的文档中(https://github.com/vipshop/Saturn/wiki/Start-the-dashboard-module)的最后部分,有如下这段话:
SATURN_CONSOLE_DB_URL: such as jdbc:mysql://a.b.c.d:3306/saturn_console

如果直接复制黏贴的话会遇到一个问题:
 jdbc:mysql://a.b.c.d:3306/saturn_console  这一段的":"冒号,第一个和第二个不一致(第二个是错的,应该是输入法全角跟半角的问题). 会导致console启动的时候一直报mysql的连接错误.

**Comment by kfchu** [comment]
貌似没有问题啊。
