### ISSUE TITLE
文档介绍不清晰，都不知道怎么quickstart

### ISSUE THREAD

**Issue by rumly** [vipshop/Saturn#165]
Saturn/quickstart/quickstart.bat
这个文件执行报错，另外，在执行这个文件前要做什么吗？文件是从什么地方获取，要自己编译么？

**Comment by rumly** [comment]
哎，自己环境的问题，双击启动quickstart.bat提示找不到mvn命令，从CMD执行quickstart.bat就可以了。

**Comment by JeremyLinTqmall** [comment]
没有提供Mac OS环境下启动的方案么
