### ISSUE TITLE
It is recommended to provide command-line options for custom log output paths

### ISSUE THREAD

**Issue by xiaoxing598** [vipshop/Saturn#170]
## bin/saturn-executor.sh

```
83 LOGDIR=/apps/logs/saturn/${NAMESPACE}/${EXECUTORNAME}-${LOCALIP}
```
Everyone has a different environment, and this path can be customized `/apps/logs/saturn`.It is too convenient if you can specify the command line parameters.

**Comment by hebelala** [comment]
You can set the jvmArgs or env parameter with `SATURN_LOG_DIR`, the executor log directory will be there, but the `saturn-executor.log` is still in `/apps/logs/saturn/${NAMESPACE}/${EXECUTORNAME}-${LOCALIP}`.

**Comment by xiaoxing598** [comment]
I think we can expose a variable out to set, after all, everyone's environment is not the same, to do this is actually very simple.

**Comment by hebelala** [comment]
@xiaoxing598 Could you test it?

**Comment by xiaoxing598** [comment]
These parameters seem to have no effect?

```
[xxx@VM_x_centos tmp]$ ./saturn-executor.sh -sdl '/tmp'
LOGDIR:/apps/logs/saturn//VM_x_centos-10.10.13.16
\n
OUTFILE:/apps/logs/saturn//VM_x_centos-10.10.13.16/saturn-executor.log
```

I only made a simple output.

```
if [[ "$LOGDIR" = "" ]]; then
  LOGDIR=/apps/logs/saturn/${NAMESPACE}/${EXECUTORNAME}-${LOCALIP}
fi

OUTFILE=$LOGDIR/saturn-executor.log
echo 'LOGDIR:'$LOGDIR;
echo '\n';
echo 'OUTFILE:'$OUTFILE;
exit;
```

**Comment by hebelala** [comment]
@xiaoxing598 You should executor with `start` command, like ./saturn-executor.sh -sdl start '/tmp'. It will work.

Attention, the v2.1.0 have released, but the -sdl is spelling mistake, it should be -sld. In the next version, it will be fixed. You should use --saturnLogDir in v2.1.0. Thanks!

**Comment by xiaoxing598** [comment]
Well, it works fine. I tested it

**Comment by hebelala** [comment]
@xiaoxing598 Now, you could use v2.1.0.1, -sld can be used.
