### ISSUE TITLE
saturn-job-spring-demo/pom.xml中的依赖

### ISSUE THREAD

**Issue by muercy** [vipshop/Saturn#172]
saturn-job-spring-demo/pom.xml中的依赖
`<dependency>
	<groupId>com.vip.saturn</groupId>
	<artifactId>saturn-job-embed</artifactId>
	<version>${saturn-job.version}</version>
	<scope>test</scope>
</dependency>`
其中artifactId应改为<artifactId>saturn-embed</artifactId>，否则下不到包

**Comment by hebelala** [comment]
好的，谢谢
