### ISSUE TITLE
Shell job return exception during execution

### ISSUE THREAD

**Issue by kfchu** [vipshop/Saturn#204]
This bug do not impact the execution result.

The root cause is that our code cannot perfectly handle the system environment which have LF.
For example, if the system environment variable contains:

BASH_FUNC_lsof()=() {  /usr/sbin/lsof -n $@\n}\n

Then, error response will be returned as below:

[demoShellJob] msg=demoShellJob-0:/bin/sh: lsof: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_lsof'

**Comment by hebelala** [comment]
https://github.com/vipshop/Saturn/commit/d33ad79d128cdc383053570f89f2f28801f31d95
