### ISSUE TITLE
The executor generated too many logs

### ISSUE THREAD

**Issue by xiaoxing598** [vipshop/Saturn#205]
I hope that the log level can be specified by script parameters, the current level is INFO, which produces up to several G log files, and I do not care about these logs unless they have a warning or error.

I also do not want to manually compile the program to achieve the purpose, if you can execute the script, by specifying the parameters to change the log output level that would be great.

**Comment by hebelala** [comment]
The executor classloader is different from the job classloader, so the job log is custom by yourself.
Maybe you used the ConsoleAppender, please don't use it.

**Comment by xiaoxing598** [comment]
I am directly downloading the installation package you are building and using the documentation recommended steps if you want to modify the log input level profile, does this mean that I want to re-build locally, I might have to install Maven, which for me really trouble , Especially for developers who do not have Java. (Even if i will be Java)

**Comment by hebelala** [comment]
Are you using Java job, or Shell job?

**Comment by xiaoxing598** [comment]
I use Shell Job. When should I specify the log output level?

**Comment by hebelala** [comment]
saturn executor cannot take over the shell job's log, the shell job should deal with it well. The important thing is, cannot use `echo, print, etc` to the standard out.
