### ISSUE TITLE
saturn worker consumes high CPU when Cron describes a past time

### ISSUE THREAD

**Issue by Jaskey** [vipshop/Saturn#224]
The problem occurs in the while logic when determine when to handle tasks.

		while (!halted.get()) {
			try {
				synchronized (sigLock) {
					while (paused && !halted.get()) {
						try {
							sigLock.wait(1000L);
						} catch (InterruptedException ignore) {
						}
					}
					if (halted.get()) {
						break;
					}
				}
				boolean noFireTime = false; // 没有下次执行时间，初始化为false
				long timeUntilTrigger = 1000;
				if(triggerObj != null){
					triggerObj.updateAfterMisfire(null);
					long now = System.currentTimeMillis();
					Date nextFireTime = triggerObj.getNextFireTime();
					if(nextFireTime != null) {
                        timeUntilTrigger = nextFireTime.getTime() - now;
                    } else {
                        noFireTime = true;
                    }
				}
				
				while (!noFireTime && timeUntilTrigger > 2) {
					synchronized (sigLock) {
						if (halted.get()) {
							break;
						}
						if (triggered){
							break;
						}
						
						try {
							sigLock.wait(timeUntilTrigger);
						} catch (InterruptedException ignore) {
						}
						
						if(triggerObj != null){
							long now = System.currentTimeMillis();
                            Date nextFireTime = triggerObj.getNextFireTime();
                            if(nextFireTime != null) {
                                timeUntilTrigger = nextFireTime.getTime() - now;
                            } else {
                                noFireTime = true;
                            }
						}
					}
				}
				boolean goAhead;
				// 触发执行只有两个条件：1.时间到了；2。点立即执行；
				synchronized (sigLock) {
					goAhead = !halted.get() && !paused;
					// 重置立即执行标志；
					if (triggered) {
						triggered = false;
					} else { // 非立即执行。即，执行时间到了，或者没有下次执行时间。
                        goAhead = goAhead && !noFireTime;
                        if(goAhead && triggerObj != null) { // 执行时间到了，更新执行时间；没有下次执行时间，不更新时间，并且不执行作业
                            triggerObj.triggered(null);
                        }
                    }
				}
				if (goAhead) {
					job.execute();
				}
				
			} catch (RuntimeException e) {
				log.error(String.format(SaturnConstant.ERROR_LOG_FORMAT, job.getJobName(), e.getMessage()), e);
			}
		}

As long as the job is not stopped(`!halted.get()`), a 
```
    while(true){
        //doSomething();
    ;}
```

will always be triggered  for each job. However, for a task will never schedule again in the future, this while loop is meaningfulness for  most of the time only ends with acquire the lock then release the lock and again and again without any pause.

A simple solution will be add `sleep` in the end of the loop to prevent busy cpu consumption.

**Comment by hebelala** [comment]
It seems to make sense, have you tested it to prove this problem?  what is the CPU usage rate?

**Comment by Jaskey** [comment]
it could be easily test to make a job that will  never be triggered any more. Only one job will take 20% CPU in my Windows machine. 

The same problem have been obliviously found in our Linux production environment when delay jobs will never be triggered again. For now, we just stop the delay job after they are triggered as a workaround.

**Comment by hebelala** [comment]
I have just tested it. Yes, you are right!  

My computer's time is 2017-09-11 16:00:00.   
 
When the cron is `0 15 11 11 09 ? 2017`,  `top` show:  

![top1](https://user-images.githubusercontent.com/22008307/30264693-2ad0d598-970c-11e7-8e94-ba2d53a6a96f.png)


When the cron is `0 15 11 11 * ? 2017`, `top` show:    

![top2](https://user-images.githubusercontent.com/22008307/30264699-3485891c-970c-11e7-83f3-5ca0ad8fbb48.png)

**Comment by hebelala** [comment]
After I commit the new code, the cpu usage is normal, the `top` result as follows:    

![newtop1](https://user-images.githubusercontent.com/22008307/30264874-ed6894f6-970c-11e7-8576-b9f42722df09.png)

![newtop2](https://user-images.githubusercontent.com/22008307/30264885-f6844012-970c-11e7-81d9-86ee673608ce.png)

**Comment by hebelala** [comment]
@Jaskey Please review the code, or test it

**Comment by Jaskey** [comment]
I believe, sleep is enough, no need to call wait which needs the lock. Please refer to my pr https://github.com/vipshop/Saturn/pulls a week ago

**Comment by hebelala** [comment]
I have looked your pull request. I don't think so.   
The sleep or wait time should be 1000 ms, Because saturn just support the cron min time that is a second. So the 1000 ms is reasonable, but your 100 ms is not.  And, use the `sigLock.wait(1000L)`,  the `sigLock` is necessary, because it can be notified, and no need to wait. And, you said the lock which is unnecessary, but I think, the lock is already existing,  I just reuse it.

**Comment by Jaskey** [comment]
@hebelala allright then
