### ISSUE TITLE
Communications link failure

### ISSUE THREAD

**Issue by hebelala** [vipshop/Saturn#256]
set minEvictableIdleTimeMillis

**Comment by lanjane** [comment]
@hebelala the same question appears 
![image](https://user-images.githubusercontent.com/30588774/35267225-8bbf0772-0060-11e8-9e36-ded443a28d42.png)

**Comment by hebelala** [comment]
使用 druid 官方参考配置，https://github.com/alibaba/druid/wiki/配置_DruidDataSource参考配置
