### ISSUE TITLE
Clean up quartz dependencies

### ISSUE THREAD

**Issue by kfchu** [vipshop/Saturn#267]

**Comment by duffqiu** [comment]
for example : 
https://github.com/vipshop/Saturn/blob/develop/saturn-core/src/main/java/com/vip/saturn/job/exception/JobShuttingDownException.java
去掉继承关系

需要全局扫描以下quartz的包引入的地方

**Comment by kfchu** [comment]
remove quartz dependency in JobShuttingDownException
  https://github.com/vipshop/Saturn/commit/421c2473cdcb9a2edbdc4eb6a9223bb983267c69

**Comment by kfchu** [comment]
remove redundant code https://github.com/vipshop/Saturn/commit/3225223af3e1fe9175c9dc70e57a0e47f46be28f
