### ISSUE TITLE
the job-sharding seems not work when i create a new job?

### ISSUE THREAD

**Issue by SilentOrangutan** [vipshop/Saturn#274]
version 2.1.4
![2017-10-30 17-27-20](https://user-images.githubusercontent.com/11172765/32163828-83f4e1e8-bd98-11e7-9ff8-533498c41b2c.png)

i followed the wiki step by step and everything goes well until i create a new job in the console,
![2017-10-30 17-25-43](https://user-images.githubusercontent.com/11172765/32163781-614d649e-bd98-11e7-8793-896f228dfa38.png)
![2017-10-30 17-26-35](https://user-images.githubusercontent.com/11172765/32163825-82f80df6-bd98-11e7-95e6-c0bbf5a86718.png)

there is nothing in the 'console' and 'execute' log,i have no idea to debug it..

**Comment by kfchu** [comment]
Hi Orangutan, could you tell me what kind of job you create ? Java or Shell ?

For Java, please make sure that your executor contains the job class you implemented.

**Comment by SilentOrangutan** [comment]
Thanks for return@kfchu, it's Shell Job ,and i can run it in the local server,the job status always in 'READY' in console
