### ISSUE TITLE
Saturn2.1.2后面版本安装部署疑惑

### ISSUE THREAD

**Issue by czj1992** [vipshop/Saturn#279]
是不是我在从Saturn Release下载saturn console 2.1.2版本或更新的版本的jar。根据 Saturn2.1.2版本升级指南设置就好，不需要设置regcenter.json文件？

运行console 2.1.4jar, 报

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.4.0.RELEASE)

log4j:WARN No appenders could be found for logger (com.alibaba.druid.pool.DruidAbstractDataSource).
log4j:WARN Please initialize the log4j system properly.

请问知道什么原因吗？

**Comment by lanjane** [comment]
运行saturn-console-2.1.3-exec.jar ,不需要配置regecenter.json文件，改从mysql数据库读取zk_cluster_info表。
