### ISSUE TITLE
getCachedAddressException:java.lang.Exception: wrong with get ip cause by could not read any info from local host, bond0 and eth0

### ISSUE THREAD

**Issue by czj1992** [vipshop/Saturn#280]
linux虚拟机跑的Executor：
报：getCachedAddressException:java.lang.Exception: wrong with get ip cause by could not read any info from local host, bond0 and eth0
刚学习，有点菜鸟，请指教下

**Comment by duffqiu** [comment]
你的网卡并不在bond0, eth0上，默认的linux安装的网卡的名称不是eth0
两种方式，一个改网卡名称，一个改下代码读ip那里

**Comment by czj1992** [comment]
谢谢你，是不是我去liunx把网卡名称，改成"bond0"," eth0",
或者我把源代码的里面的 bond0，eth0改成我网卡的名称？
NetworkInterface ni = NetworkInterface.getByName("bond0");
					if (ni == null) {
						ni = NetworkInterface.getByName("eth0");
}

是这样的理解的吗？

**Comment by czj1992** [comment]
已按照改好，用linux命令改网卡名称为eth0。
