### ISSUE TITLE
2.1.2 的VIP_SATURN_CONSOLE_URI变量值问题

### ISSUE THREAD

**Issue by czj1992** [vipshop/Saturn#284]
文档上说VIP_SATURN_CONSOLE_URI（指向Saturn Console的访问url，多个使用英文逗号隔开）。
我console服务器的ip是192.168.16.133。
是下面这样设置吗？
export VIP_SATURN_CONSOLE_URI=http://192.168.16.133:9088/

还是这样的设置：
export VIP_SATURN_CONSOLE_URI=VIP_SATURN_CONSOLE_CLUSTER(每台Console的集群ID)

**Comment by kfchu** [comment]
前者正确。如果有多个就逗号隔开。
