### ISSUE TITLE
ShardingListenerManager的shutdown方法没有remove ConnectionStateListener

### ISSUE THREAD

**Issue by addozhang** [vipshop/Saturn#287]
JobScheduler实例创建的时候会启动ShardingListenerManager, 并添加了一个ConnectionStateListener.

如果createJob()无法找到对应的jobClass, 抛出异常. 最终会调用ShardingListenerManager.shutdown. 
如果不remove ConnectionStateListener, 这个JobScheduler实例会被ConnectionStateManager实例引用, 不会被GC回收.

因此ShardingListenerManager.shutdown方法中调用removeConnectionStateListener.

**Comment by addozhang** [comment]
不被GC回收还有其他的隐患, necessary watcher还会存在.

**Comment by hebelala** [comment]
@addozhang 麻烦review我提交的代码，看有没有问题
