### ISSUE TITLE
NamespaceShardingService类中bug

### ISSUE THREAD

**Issue by codeyuan** [vipshop/Saturn#293]
Collections.sort(itemList, new Comparator<Integer>() {
 				@Override
 				public int compare(Integer o1, Integer o2) {
-					return 01 - 02;
+					return o1 - o2;
 				}

**Comment by codeyuan** [comment]
01-02改为o1-o2

**Comment by hebelala** [comment]
Yeah, it's a problem. But, actually, this sort operation is not meaningful.

**Comment by codeyuan** [comment]
ok,thank you!
