### ISSUE TITLE
作业执行总数上报并发存在问题

### ISSUE THREAD

**Issue by addozhang** [vipshop/Saturn#294]
AnalyseService里的代码, totalCount和errorCount都是先读本地计算再写回zk. 如果多executor并发操作时, 会出现问题.

建议使用Curator的DistributedAtomicValue实现类似原子操作. AnalyseService线程是异步写zk的, 因此对性能影响不大. RetryPolicy可以使用RetryForever加上interval.

**Comment by kfchu** [comment]
谢谢你的建议。确实有并发问题，我们排一下计划去fix这个问题。
