### ISSUE TITLE
Saturn job开发支持动态部署吗？

### ISSUE THREAD

**Issue by mogong** [vipshop/Saturn#302]
请问下 我开发好一个job，放到对应的目录下，在控制台配置好后，不能动态加载吗？

**Comment by kfchu** [comment]
现在没有。但3.0有计划做这个，具体时间还是要plan一下。

**Comment by kfchu** [comment]
@iKenApple 看看今年Q4我们是否能做。不过目前确实没有时间表。请关注我们的release note。谢谢！

**Comment by iKenApple** [comment]
@kfchu 谢谢
