### ISSUE TITLE
请问作业的 namespace 和 name 之间有什么关系吗？

### ISSUE THREAD

**Issue by codeyuan** [vipshop/Saturn#324]

**Comment by kfchu** [comment]
namespace 是业务域，包含若干作业。具体可以参看这里：https://github.com/vipshop/Saturn/wiki/Saturn%E6%9E%B6%E6%9E%84%E6%96%87%E6%A1%A3

**Comment by codeyuan** [comment]
那name指的是什么呢

**Comment by kfchu** [comment]
@codeyuan name具体在哪里出现？哪个文档？

**Comment by codeyuan** [comment]
不好意思，看错了，是group和namespace的关系是什么？

**Comment by codeyuan** [comment]
RegistryCenterConfiguration类中的name 和namespace 的关系是什么？
