### ISSUE TITLE
Console support Authentication

### ISSUE THREAD

**Issue by hebelala** [vipshop/Saturn#359]
新增用户表：

字段名 | 类型 | 描述
-- | -- | --
id |   |  
user_name|   |  
password|   |  
real_name|   |  
employee_id |   |  
email |   |  
create_time |   |  
created_by |   |  
last_update_time |   |  
last_updated_by |   |  
is_deleted |   |

**Comment by kfchu** [comment]
3.0.0 功能开发另外开一个issue：#398
