### ISSUE TITLE
REST API遇到异常情况返回错误的status code

### ISSUE THREAD

**Issue by kfchu** [vipshop/Saturn#387]
Create Job:

当job 已经存在返回500，应为400
当job 超过最大数量返回500，应为400
当job 参数类型有误，（例如本地模式分片数包含*）返回500，应为400

**Comment by kfchu** [comment]
@hebelala please help to review

**Comment by kfchu** [comment]
@hebelala please help to review

**Comment by leewcc** [comment]
提交关联 补IT
https://github.com/vipshop/Saturn/commit/02c0eb7bdd4a6d1ec62bf7ccce3579b7745fe516
https://github.com/vipshop/Saturn/commit/83206bf41134c1cc701d4ec8219aff3f9b3f3699
