### ISSUE TITLE
Job business thread should be interrupted before stop during force stop

### ISSUE THREAD

**Issue by kfchu** [vipshop/Saturn#411]
Executor 强杀时，应该先进行interrupt再stop thread

**Comment by hebelala** [comment]
循环interrupt，每隔50ms中断一次，如果业务线程结束或者中断次数超过100次，循环结束。 如果业务线程结束，则不需要stop，否则仍然stop thread。

**Comment by kfchu** [comment]
@hebelala please review my commit.
