### ISSUE TITLE
添加集群后列表没显示，数据库却有记录

### ISSUE THREAD

**Issue by happyapple668** [vipshop/Saturn#449]
我在注册中心-ZK集群管理里面添加了ZK集群，点击第一次确定，窗口没消息，又点了确定，提示已存在，并且窗口消失后，在列表里面看不到有记录。然后在数据库表zk_cluster_info里面有一条记录。这是bug吗？？？还是只有我是这样的？我用的是3.0.1.zip

**Comment by iKenApple** [comment]
你需要刷新或者等一会儿

**Comment by happyapple668** [comment]
我是到现在都没记录~

**Comment by happyapple668** [comment]
我是过了几小时后再看都没数据的~果断放弃了

**Comment by happyapple668** [comment]
我当时也刷新了，过了几小时后一样没变化啊~

**Comment by luckysky369** [comment]
是的，这个问题我也遇到了，导致的结果是数据库里面有数据，列表没显示

**Comment by cmzdandan** [comment]
我也遇到了这样的情况，过多久都没有反应，点刷新仍然不显示

**Comment by pkpk1234** [comment]
我也遇到这个问题了，自己用源码build后运行又是正常的。

**Comment by happyapple668** [comment]
这个问题还没解决吗？我就是用的源码mvn package打包的，还是这样子

**Comment by happyapple668** [comment]
Saturn-3.1.1.zip

**Comment by GreedyPirate** [comment]
同样的问题，请问有人解决了吗
