### ISSUE TITLE
如何定义任务失败告警策略

### ISSUE THREAD

**Issue by hiddletian** [vipshop/Saturn#456]
作业失败的告警策略的前提是必须定义作业等级嘛？关于配置告警策略这块有没有相关的文档资料？

**Comment by iKenApple** [comment]
@hiddletian 我在这里找到了一点说明，[作业告警](https://github.com/vipshop/Saturn/wiki/Job-Management-Rest-Api)

是不是实现raise函数就能自定义报警？

**Comment by hiddletian** [comment]
@iKenApple 我这边选用的是3.0.1的版本，你提供这个链接我之前有看过，我用接口查询就没看到定义作业等级的字段，页面上没有，对java不太熟

**Comment by hiddletian** [comment]
@iKenApple 知道了，这个就是你说的这样 https://github.com/vipshop/Saturn/wiki/Use-Custom-Event-Alarm
