### ISSUE TITLE
Executor加载Java实现类的时候,实现类里有Spring注入的对象,报错

### ISSUE THREAD

**Issue by GaoSaturn** [vipshop/Saturn#462]
Executor加载Java实现类的时候,实现类里有Spring注入的对象,报错java.lang.reflect.InvocationTargetExeception:null
是不会预先加载spring管理的对象吗?比较急,跪求解答

**Comment by 468120308** [comment]
我也遇到了相同的问题，请教各位大神，该如何处理。

**Comment by 468120308** [comment]
已解决:参照example中spring-demo工程SpringFactory类文件。
