### ISSUE TITLE
运行状态栏的日志查看为空是？

### ISSUE THREAD

**Issue by hiddletian** [vipshop/Saturn#463]
![image](https://user-images.githubusercontent.com/24969450/42986994-487b33ea-8c2a-11e8-8e09-4b08e4a5bf16.png)
截图中的日志具体是记录什么的呢？我看一直是空

**Comment by kfchu** [comment]
启用高级配置里面的“控制台输出日志”就会有console的log打印在这里。

详情看这里：https://vipshop.github.io/Saturn/#/zh-cn/3.0/create_job?id=_4%E8%AF%A6%E7%BB%86%E4%BD%9C%E4%B8%9A%E8%AE%BE%E7%BD%AE

**Comment by hiddletian** [comment]
@kfchu 好的，多谢  作业的执行日志能看到嘛？内似于linux下cron的日志/var/log/cron

**Comment by kfchu** [comment]
@hiddletian 作业执行日志在每台executor的日志里面(saturn-executor-log.log)。每次调度的开始和结束，我们都会记录日志。

**Comment by hiddletian** [comment]
@kfchu 收到，灰常感谢
