### ISSUE TITLE
3.1.0版本无法找到报警设置

### ISSUE THREAD

**Issue by liubotao** [vipshop/Saturn#476]
版本: 3.1.0
场景: 在作业中心添加新的作业，添加分片参数0=php /home/hlg/tmp/test.php; test.php为异常错误脚本，执行的时候，运行状态为失败，日志显示脚本错误。我想设置此脚本失败的时候能够告警。我尝试在任务基础配置和高级配置中寻找，但是最终找寻无果。我又到job_config里面将任务的degree改为4。但是还是未效果；请问下要怎么设置才可以达到我的目的。

**Comment by kfchu** [comment]
@liubotao 在SaturnJobReturn里面，将errorGroup设置为551即可发送告警。详情参见AbstractSaturnJob#updateExecuteResult 方法
