### ISSUE TITLE
zk集群缓存删了重启zk集群job就无法执行了???

### ISSUE THREAD

**Issue by R1hug0** [vipshop/Saturn#482]
碰到一个现象,在测试的时候把zk的缓存数据删除了,然后重启zk集群发现job不能执行了,但在console界面查看都存在,对比了一下导出发现Job导出的都是空的只有一个Jobname,但在数据库查看Job内容都有,难道zk重建就不会从数据库把已存的Job重新导入一份写入zk里面吗,版本3.0.1

**Comment by kfchu** [comment]
@R1hug0 你所说的zk缓存是指什么？？

**Comment by R1hug0** [comment]
就是zk集群里面保存的数据,  这个设计是以zk为持久存储,db为辅?

**Comment by kfchu** [comment]
@R1hug0 console的数据有2类，一类是配置型的，从DB读取，另外一类是临时的数据，例如运行状态，这是从ZK读取。而executor只会从ZK读取数据。
