### ISSUE TITLE
执行器莫名多出一个127.0.1.1的地址来,也没法删除

### ISSUE THREAD

**Issue by R1hug0** [vipshop/Saturn#524]
这个怎么排查原因呢,好象也找不到头绪,能指导下吗
![127](https://user-images.githubusercontent.com/8827342/47127815-3edd1f00-d2c1-11e8-984a-8ee080730831.png)

**Comment by kfchu** [comment]
@R1hug0 没遇过，你是嵌入式启动？是不是调用了2次？debug一下？

**Comment by R1hug0** [comment]
没办法复现,半个月了每个注册的域下面都多了一个这样的注册地址出来.查看日志也没发现怎么注册上去的

**Comment by R1hug0** [comment]
![ss](https://user-images.githubusercontent.com/8827342/47987832-82d27f80-e11b-11e8-8342-434bcf88d62e.jpg)

**Comment by kfchu** [comment]
@R1hug0 在线是不能删除的

**Comment by R1hug0** [comment]
最主要是不知道这个IP是怎么出来的,没有机器的地址是127.0.1.1,在开发环境也没有复现出来.能给点解决问题思路吗.

**Comment by R1hug0** [comment]
![default](https://user-images.githubusercontent.com/8827342/48813983-1048dd00-ed74-11e8-986d-ef8d07ddeb4f.png)
 能给点思路解决吗

**Comment by R1hug0** [comment]
@kfchu 看看,始终找不到127.0.1.1这个IP怎么生成的

**Comment by R1hug0** [comment]
找到原因了,代码中获取IP方式有问题没有对获取的IP进行断判,单纯使用/etc/hosts中解析
