### ISSUE TITLE
疑问：某个JOB 需要分片20个节点运行，如果JOB的包有更新了，那么所有的executor都要更新重启吗？

### ISSUE THREAD

**Issue by zlzforever** [vipshop/Saturn#528]
1. executor是否会扫描本地目录下的app包然后注册到ZK上，这样没有相应app包的executor则不会参与调度
2. 强依赖的java job, 如果一个executor下有多个不同版本的包，会出问题吧？

**Comment by kfchu** [comment]
@zlzforever 1. 没有作业类的不参与调度 2. 不同版本的job class有可能引起类冲突，因为都是share一个classloader的
