### ISSUE TITLE
CONSOLE_ZK_CLUSTER_MAPPING 不配置，查不到ZK集群信息

### ISSUE THREAD

**Issue by lzw2006** [vipshop/Saturn#558]

**Comment by Rebellioncry** [comment]
问题解决了吗老铁？我添加zookeeper集群提示成功但是没有列表没有显示在线，也不能配置CONSOLE_ZK_CLUSTER_MAPPING，会报错

**Comment by kfchu** [comment]
可以把CONSOLE_ZK_CLUSTER_MAPPING（value为空）添加到默认安装的schema里面
