### ISSUE TITLE
“API与命令参数详解”一栏怎么没有内容？

### ISSUE THREAD

**Issue by Rebellioncry** [vipshop/Saturn#561]
想通过调用api来创建任务，但是开发文档中找不到，于是根据https://github.com/vipshop/Saturn/issues/326 我增加了"--spring.profiles.active=dev"，启动日志也显示Mapped "{[/swagger-ui.html],methods=[GET]}"，但是访问"http://ip:9088/swagger-ui.html"显示找不到网页。我是哪里弄错了吗？

**Comment by kfchu** [comment]
看起来没啥毛病

**Comment by Rebellioncry** [comment]
@kfchu 有没有api开发文档啊，“API与命令参数详解”一栏怎么没有内容，我想用api来创建任务调度

**Comment by kfchu** [comment]
@Rebellioncry https://github.com/vipshop/Saturn/wiki/Job-Management-Rest-Api

**Comment by Rebellioncry** [comment]
@kfchu thank you for your reply
