### ISSUE TITLE
为什么要依赖Docker，是强依赖吗？无疑增加部署难度

### ISSUE THREAD

**Issue by yuxiao97** [vipshop/Saturn#564]
为什么要依赖Docker，是强依赖吗？无疑增加部署难度

**Comment by kfchu** [comment]
并没有。docker只是我们quick study的一个sample

**Comment by yuxiao97** [comment]
> 并没有。docker只是我们quick study的一个sample

嗯，看文档的时候还以为强依赖呢，谢谢~
