### ISSUE TITLE
问：任务执行失败，是否支持发送邮件？

### ISSUE THREAD

**Issue by GuoHuiChen** [vipshop/Saturn#566]

**Comment by GuoHuiChen** [comment]
谢谢！

**Comment by GuoHuiChen** [comment]
我看了一下，还是不懂怎么实现， 是否有一个例子？
如果自己设想发送邮件， 这个代码，我是否应该放在console里面，还是写在executor的JOB相应类里面？
实现这个接口：ReportAlarmService，还是哪个？

**Comment by iKenApple** [comment]
@kfchu 是不是还需要修改saturn console获取到551错误码后的处理方式，具体是否是修改SaturnJavaJob.java#onNeedRaiseAlarm?谢谢！

**Comment by iKenApple** [comment]
需要修改ReportAlarmServiceImpl.java#rasie()，谢谢

**Comment by iKenApple** [comment]
我知道问题在哪里了，确实是只需要实现raise()就行，谢谢！
