### ISSUE TITLE
是否支持IOT场景大量任务并发调度

### ISSUE THREAD

**Issue by shenrabbit** [vipshop/Saturn#620]
IOT场景下存在大量设备，如果由服务器端实现各设备定时任务调度，Saturn框架能否支持？或者支持1000万定时任务需要多少服务器支持？

**Comment by kfchu** [comment]
频率有多高？

**Comment by shenrabbit** [comment]
每【组/个】设备一天会被调度执行几次任务，比如简单的定时开灯、关灯，以及其他一些不方便在设备端实现的定时需求。

**Comment by kfchu** [comment]
一天几次任务的不是问题，对于没有定时需求的，可以考虑使用消息队列去处理。
