### ISSUE TITLE
 saturn version 3.3.1 and 3.3.2 無法正確執行 Job

### ISSUE THREAD

**Issue by HKChen** [vipshop/Saturn#634]
使用 release 3.3.1 和最新的測試 3.3.2 版本，在執行 Job 的時候都會出現
triggeredData=null，降回 3.3.0 版本就可以正常。

**Comment by kfchu** [comment]
是什么类型的作业，配置有什么特殊的地方吗？

**Comment by HKChen** [comment]
> 是什么类型的作业，配置有什么特殊的地方吗？

一般的作業在舊版都可以正常執行，目前就依舊版執行沒有在使用最新版了。 Thx
