### ISSUE TITLE
关于job是由spring管理的问题

### ISSUE THREAD

**Issue by skyleft** [vipshop/Saturn#74]
你好，我这边采用了Saturn来管理job，有个问题是job是由spring管理的bean，
我实现getObject方法，对于每一个job都要单独启动spring容器来获取这个bean，
这样不论是job的维护上还是执行的效率上都会有很大影响，请问有什么方法吗？

**Comment by dylanxue** [comment]
多个作业可以共用同一个spring实例的，spring通常只需要初始化一次，全部作业的getObject()方法从这个全局的spring实例中获取对象。不需要为每个作业都初始化一份spring容器。

**Comment by skyleft** [comment]
好的 谢谢 我试一下
