### ISSUE TITLE
How do I deploy new job to executor ?? this may affect the exit job in the executor ??

### ISSUE THREAD

**Issue by Ah39** [vipshop/Saturn#76]
One machine with one executor with more than one job ???
How do I deploy new job to executor ??
First stop executor , then add zip to app DIR ,then start executor with more than one job ??
this may affect the exit job in the executor ??

**Comment by dylanxue** [comment]
通常情况下，多个作业是一起发布到executor下面的；因此如果是增量添加作业，是需要把jar或目录放到app目录下，然后重启executor的。这个动作确实是会影响到现有作业。未来saturn会考虑引进动态加载作业功能，避免executor频繁重启。

**Comment by Ah39** [comment]
不能考虑每次新加job，都是新启动一个executor吗，类似tomcat启动新的应用？ 多个job在executor下面运行，同一个jvm中，不能做到隔离，会相互影响。还有一个问题，如果两个job的实现类相同，saturn，能做区分吗？# **一个executor运行多个job，每一个job都需要一个classload**。

**Comment by dylanxue** [comment]
saturn的隔离原则是namespace隔离，即一个namespace下面的job都是同一个classloader的。如果你需要两个job隔离，可以启动两个executor,传入不同的namespace即可。
executor运行时是非常轻量的，一台机器上面跑多个executor是完全没问题的。

**Comment by duffqiu** [comment]
作业与executor一对一的隔离，我们后面是考虑用容器的方式处理，不是在jvm这个层面上做
