### ISSUE TITLE
dependency can't find for saturn-job-spring-demo project

### ISSUE THREAD

**Issue by bingguichen** [vipshop/Saturn#98]
Can't find the saturn-job-embed dependency in pom.xml, is it a spell issue? is it saturn-embed, right?

**Comment by dylanxue** [comment]
you are right !
Which file that you find that problem？

**Comment by foxdd** [comment]
same problem at all saturn spring job demo project

**Comment by foxdd** [comment]
sry name updated，pom.xml of saturn spring job demo
